# Generated by Django 5.2.11 on 2026-02-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registrojornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrojornada',
            name='horas_trabajadas',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
