# Generated by Django 5.2.11 on 2026-02-17 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registrojornada_horas_trabajadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('universidad', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio_practica', models.DateField(blank=True, null=True)),
                ('fecha_termino_practica', models.DateField(blank=True, null=True)),
                ('horas_requeridas', models.IntegerField(blank=True, null=True)),
                ('es_controller', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
