# Generated by Django 5.2.11 on 2026-02-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reporteavance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicante',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
