# Generated by Django 5.2.11 on 2026-02-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_practicante_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicante',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='practicante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
