# Generated by Django 5.2.11 on 2026-02-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_practicante_celular_practicante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteavance',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
