# Generated by Django 6.0.3 on 2026-04-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='sugerencias_multimedia/'),
        ),
    ]
