# Generated by Django 6.0.3 on 2026-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('leida', 'Leida'), ('finalizada', 'Finalizada')], default='enviada', max_length=20),
        ),
    ]
