# Generated by Django 6.0.2 on 2026-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sugerencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='sugerencias_multimedia/'),
        ),
    ]
