# Generated by Django 6.0.2 on 2026-04-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sugerencia_archivo_adjunto'),
        ('core', '0013_sugerencia_estado'),
    ]

    operations = [
    ]
